<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>HELLOGUI</name>
    <message>
      <source>MEN_FILE</source>
      <translation>ファイル(&amp;F)</translation>
    </message>
    <message>
      <source>MEN_FILE_HELLO</source>
      <translation>こんにちは</translation>
    </message>
    <message>
      <source>MEN_HELLO</source>
      <translation>こんにちは</translation>
    </message>
    <message>
      <source>MEN_OP_HELLO</source>
      <translation>こんにちは</translation>
    </message>
    <message>
      <source>MEN_OP_GOODBYE</source>
      <translation>さようなら</translation>
    </message>
    <message>
      <source>MEN_OP_TESTME</source>
      <translation>私にください。</translation>
    </message>
    <message>
      <source>STS_OP_HELLO</source>
      <translation>サロメを歓迎します。</translation>
    </message>
    <message>
      <source>STS_OP_GOODBYE</source>
      <translation>サロメにさよならを言う</translation>
    </message>
    <message>
      <source>STS_OP_TESTME</source>
      <translation>カスタム メニュー アクションのテスト</translation>
    </message>
    <message>
      <source>TLT_OP_HELLO</source>
      <translation>Salut à 遠い ！</translation>
    </message>
    <message>
      <source>TLT_OP_GOODBYE</source>
      <translation>さようなら！</translation>
    </message>
    <message>
      <source>TLT_OP_TESTME</source>
      <translation>私にください。</translation>
    </message>
    <message>
      <source>TOOL_TEST</source>
      <translation>テスト</translation>
    </message>
    <message>
      <source>TOOL_HELLO</source>
      <translation>こんにちは</translation>
    </message>
    <message>
      <source>BUT_OK</source>
      <translation>わかりました</translation>
    </message>
    <message>
      <source>INF_TESTME_TITLE</source>
      <translation>こんにちは: 私にください。</translation>
    </message>
    <message>
      <source>INF_TESTME_MSG</source>
      <translation>カスタム メニュー アクションのテストのみです。</translation>
    </message>
    <message>
      <source>QUE_ENTER_NAME</source>
      <translation>あなたの名前を入力します。</translation>
    </message>
    <message>
      <source>QUE_HELLO_TITLE</source>
      <translation>サロメを歓迎します。</translation>
    </message>
    <message>
      <source>INF_HELLO_TITLE</source>
      <translation>こんにちは</translation>
    </message>
    <message>
      <source>INF_HELLO_MSG</source>
      <translation>救済 %1 ！</translation>
    </message>
    <message>
      <source>ERR_HELLO_ALREADY_MET</source>
      <translation>%1 はすでに知っている ！</translation>
    </message>
    <message>
      <source>ERR_ERROR</source>
      <translation>不明なエラー</translation>
    </message>
    <message>
      <source>QUE_GOODBYE_TITLE</source>
      <translation>サロメにさよならを言う</translation>
    </message>
    <message>
      <source>INF_GOODBYE_TITLE</source>
      <translation>さようなら</translation>
    </message>
    <message>
      <source>INF_GOODBYE_MSG</source>
      <translation>%1 さようなら ！</translation>
    </message>
    <message>
      <source>ERR_GOODBYE_DID_NOT_MEET</source>
      <translation>%1 はまだ出会ってません ！</translation>
    </message>
  </context>
</TS>
