<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE TS><TS language='ja' version='2.0'>
<context>
    <name>@default</name>
    <message>
        <source>Hexotic_MAX_SIZE</source>
        <translation>最大サイズ</translation>
    </message>
    <message>
        <source>Hexotic_3D_TITLE</source>
        <translation>仮定の構成</translation>
    </message>
    <message>
        <source>Hexotic_INPUT_SIZE</source>
        <translation>サイズ</translation>
    </message>
    <message>
        <source>Hexotic_SELECT_DIR</source>
        <translation>選択します.</translation>
    </message>
    <message>
        <source>Hexotic_SUBDOMAIN_MESH_MODE</source>
        <translation>サブドメインのメッシュ サイズのモード</translation>
    </message>
    <message>
        <source>Hexotic_HEXES_MIN_LEVEL</source>
        <translation>六角形の nb に登録: レベル分</translation>
    </message>
    <message>
        <source>Hexotic_IGNORE_RIDGES</source>
        <translation>尾根のない滑らかなメッシュを生成します。</translation>
    </message>
    <message>
        <source>Hexotic_ENTRY</source>
        <translation>エントリ</translation>
    </message>
    <message>
        <source>Hexotic_REMOVE</source>
        <translation>削除</translation>
    </message>
    <message>
        <source>Hexotic_MAX_MEMORY</source>
        <translation>最大メモリ (MB)</translation>
    </message>
    <message>
        <source>Hexotic_SD_MODE_1</source>
        <translation>1 つのドメイン</translation>
    </message>
    <message>
        <source>Hexotic_SD_MODE_2</source>
        <translation>虫歯は無視</translation>
    </message>
    <message>
        <source>Hexotic_SD_MODE_3</source>
        <translation>空洞メッシュ</translation>
    </message>
    <message>
        <source>Hexotic_SD_MODE_4</source>
        <translation>ジオメトリ「マニホールド」</translation>
    </message>
    <message>
        <source>Hexotic_ADD</source>
        <translation>追加</translation>
    </message>
    <message>
        <source>Hexotic_SIZE</source>
        <translation>サイズ</translation>
    </message>
    <message>
        <source>Hexotic_NAME</source>
        <translation>名前</translation>
    </message>
    <message>
        <source>Hexotic_WORKING_DIR</source>
        <translation>作業ディレクトリ</translation>
    </message>
    <message>
        <source>Hexotic_HEXES_MAX_LEVEL</source>
        <translation>六角形の nb に登録: 最大レベル</translation>
    </message>
    <message>
        <source>Hexotic_MIN_SIZE</source>
        <translation>サイズ分</translation>
    </message>
    <message>
        <source>Hexotic_VERBOSITY</source>
        <translation>詳細</translation>
    </message>
    <message>
        <source>Hexotic_SEL_SHAPE</source>
        <translation>幾何学的なオブジェクトを選択します</translation>
    </message>
    <message>
        <source>Hexotic_NB_PROC</source>
        <translation>プロセスの数</translation>
    </message>
    <message>
        <source>Hexotic_3D_HYPOTHESIS</source>
        <translation>Hexotic 3D</translation>
    </message>
    <message>
        <source>Hexotic_SHARP_ANGLE_THRESHOLD</source>
        <translation>鋭角度のしきい値</translation>
    </message>
    <message>
        <source>Hexotic_NULL_LOCAL_SIZE</source>
        <translation>0 は「ローカル サイズ」として許可されていません</translation>
    </message>
    <message>
        <source>Hexotic_INPUT_LEVEL</source>
        <translation>細分化のレベル</translation>
    </message>
    <message>
        <source>Hexotic_INVALID_ELEMENTS</source>
        <translation>無効な要素を許可します。</translation>
    </message>
</context>
</TS>
