<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.0" language="es-ES" sourcelanguage="en">
  <context>
    <name>HELLOGUI</name>
    <message>
      <source>MEN_FILE</source>
      <translation>MEN_FILE</translation>
    </message>
    <message>
      <source>MEN_FILE_HELLO</source>
      <translation>MEN_FILE_HELLO</translation>
    </message>
    <message>
      <source>MEN_HELLO</source>
      <translation>MEN_HELLO</translation>
    </message>
    <message>
      <source>MEN_OP_HELLO</source>
      <translation>MEN_OP_HELLO</translation>
    </message>
    <message>
      <source>MEN_OP_GOODBYE</source>
      <translation>MEN_OP_GOODBYE</translation>
    </message>
    <message>
      <source>MEN_OP_TESTME</source>
      <translation>MEN_OP_TESTME</translation>
    </message>
    <message>
      <source>STS_OP_HELLO</source>
      <translation>STS_OP_HELLO</translation>
    </message>
    <message>
      <source>STS_OP_GOODBYE</source>
      <translation>STS_OP_GOODBYE</translation>
    </message>
    <message>
      <source>STS_OP_TESTME</source>
      <translation>STS_OP_TESTME</translation>
    </message>
    <message>
      <source>TLT_OP_HELLO</source>
      <translation>TLT_OP_HELLO</translation>
    </message>
    <message>
      <source>TLT_OP_GOODBYE</source>
      <translation>TLT_OP_GOODBYE</translation>
    </message>
    <message>
      <source>TLT_OP_TESTME</source>
      <translation>TLT_OP_TESTME</translation>
    </message>
    <message>
      <source>TOOL_TEST</source>
      <translation>TOOL_TEST</translation>
    </message>
    <message>
      <source>TOOL_HELLO</source>
      <translation>TOOL_HELLO</translation>
    </message>
    <message>
      <source>BUT_OK</source>
      <translation>BUT_OK</translation>
    </message>
    <message>
      <source>INF_TESTME_TITLE</source>
      <translation>INF_TESTME_TITLE</translation>
    </message>
    <message>
      <source>INF_TESTME_MSG</source>
      <translation>INF_TESTME_MSG</translation>
    </message>
    <message>
      <source>QUE_ENTER_NAME</source>
      <translation>QUE_ENTER_NAME</translation>
    </message>
    <message>
      <source>QUE_HELLO_TITLE</source>
      <translation>QUE_HELLO_TITLE</translation>
    </message>
    <message>
      <source>INF_HELLO_TITLE</source>
      <translation>INF_HELLO_TITLE</translation>
    </message>
    <message>
      <source>INF_HELLO_MSG</source>
      <translation>INF_HELLO_MSG</translation>
    </message>
    <message>
      <source>ERR_HELLO_ALREADY_MET</source>
      <translation>ERR_HELLO_ALREADY_MET</translation>
    </message>
    <message>
      <source>ERR_ERROR</source>
      <translation>ERR_ERROR</translation>
    </message>
    <message>
      <source>QUE_GOODBYE_TITLE</source>
      <translation>QUE_GOODBYE_TITLE</translation>
    </message>
    <message>
      <source>INF_GOODBYE_TITLE</source>
      <translation>INF_GOODBYE_TITLE</translation>
    </message>
    <message>
      <source>INF_GOODBYE_MSG</source>
      <translation>INF_GOODBYE_MSG</translation>
    </message>
    <message>
      <source>ERR_GOODBYE_DID_NOT_MEET</source>
      <translation>ERR_GOODBYE_DID_NOT_MEET</translation>
    </message>
  </context>
</TS>
