<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS>
  <context>
    <name>@default</name>
    <message>
      <source>HEXABLOCK_ADV_ARGS</source>
      <translation>高度な</translation>
    </message>
    <message>
      <source>HEXABLOCK_HYPOTHESIS</source>
      <translation>HEXABLOCK</translation>
    </message>
    <message>
      <source>HEXABLOCK_OPTIMIZATIOL_LEVEL</source>
      <translation>最適化のレベル</translation>
    </message>
    <message>
      <source>HEXABLOCK_PERMISSION_DENIED</source>
      <translation>ディレクトリを作成することはできません。</translation>
    </message>
    <message>
      <source>HEXABLOCK_STD_ARGS</source>
      <translation>パラメーター</translation>
    </message>
    <message>
      <source>HEXABLOCK_TITLE</source>
      <translation>仮説の構築</translation>
    </message>
    <message>
      <source>HEXABLOCK_TO_MESH_HOLES</source>
      <translation>メッシュの穴</translation>
    </message>
    <message>
      <source>INIT_MEMORY_SIZE</source>
      <translation>初期メモリのサイズ、</translation>
    </message>
    <message>
      <source>KEEP_WORKING_FILES</source>
      <translation>一時ファイルを保持します。</translation>
    </message>
    <message>
      <source>LEVEL_NONE</source>
      <translation>非アクティブ</translation>
    </message>
    <message>
      <source>LEVEL_LIGHT</source>
      <translation>光</translation>
    </message>
    <message>
      <source>LEVEL_MEDIUM</source>
      <translation>(標準) の方法</translation>
    </message>
    <message>
      <source>LEVEL_STANDARDPLUS</source>
      <translation>標準</translation>
    </message>
    <message>
      <source>LEVEL_STRONG</source>
      <translation>砦</translation>
    </message>
    <message>
      <source>MAX_MEMORY_SIZE</source>
      <translation>最大メモリ サイズ</translation>
    </message>
    <message>
      <source>MEGABYTE</source>
      <translation>メガバイト</translation>
    </message>
    <message>
      <source>NO_INITIAL_CENTRAL_POINT</source>
      <translation>元の中心点を削除します。</translation>
    </message>
    <message>
      <source>RECOVERY_VERSION</source>
      <translation>バージョン境界の復元を使用します。</translation>
    </message>
    <message>
      <source>FEM_CORRECTION</source>
      <translation>使用 fix GEF</translation>
    </message>
    <message>
      <source>SELECT_DIR</source>
      <translation>...</translation>
    </message>
    <message>
      <source>TEXT_OPTION</source>
      <translation>テキスト オプション</translation>
    </message>
    <message>
      <source>TO_ADD_NODES</source>
      <translation>新しいノードを作成します。</translation>
    </message>
    <message>
      <source>VERBOSE_LEVEL</source>
      <translation>詳細レベル</translation>
    </message>
    <message>
      <source>WORKING_DIR</source>
      <translation>作業ディレクトリ</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENFORCED_VERTICES</source>
      <translation>交差点</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_X_COLUMN</source>
      <translation>X</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_Y_COLUMN</source>
      <translation>Y</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_Z_COLUMN</source>
      <translation>Z</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_SIZE_COLUMN</source>
      <translation>サイズ</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_X_LABEL</source>
      <translation>X:</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_Y_LABEL</source>
      <translation>Y:</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_Z_LABEL</source>
      <translation>Z:</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_SIZE_LABEL</source>
      <translation>サイズ:</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_VERTEX</source>
      <translation>適用された頂点を追加します。</translation>
    </message>
    <message>
      <source>HEXABLOCK_ENF_VER_REMOVE</source>
      <translation>頂点を削除します。</translation>
    </message>
  </context>
</TS>
