<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE TS><TS language='ja' version='2.0'>
<context>
    <name>GraphicsView_ViewFrame</name>
    <message>
        <source>DSC_FITSELECT</source>
        <translation>選択対象を表示するステージのサイズを変更します。</translation>
    </message>
    <message>
        <source>MNU_DUMP_VIEW</source>
        <translation>シーンを保存します。</translation>
    </message>
    <message>
        <source>MNU_PAN_VIEW</source>
        <translation>ビューのサイズを変更します。</translation>
    </message>
    <message>
        <source>DSC_GLOBALPAN_VIEW</source>
        <translation>新しいセンター ビューの選択</translation>
    </message>
    <message>
        <source>MNU_ZOOM_VIEW</source>
        <translation>ズーム</translation>
    </message>
    <message>
        <source>DSC_PAN_VIEW</source>
        <translation>ビューのサイズを変更します。</translation>
    </message>
    <message>
        <source>DSC_FITALL</source>
        <translation>すべてのオブジェクトを表示するステージのサイズを変更します。</translation>
    </message>
    <message>
        <source>MNU_FITALL</source>
        <translation>すべて表示します。</translation>
    </message>
    <message>
        <source>MNU_GLOBALPAN_VIEW</source>
        <translation>全体的なパン</translation>
    </message>
    <message>
        <source>MNU_RESET_VIEW</source>
        <translation>復元</translation>
    </message>
    <message>
        <source>DSC_FITRECT</source>
        <translation>彼の党をボックスで選択を表示するには、ステージのサイズを変更します。</translation>
    </message>
    <message>
        <source>MNU_FITRECT</source>
        <translation>[表示] ボックス</translation>
    </message>
    <message>
        <source>DSC_DUMP_VIEW</source>
        <translation>現在のシーンのイメージ ファイルに保存します。</translation>
    </message>
    <message>
        <source>MNU_FITSELECT</source>
        <translation>選択範囲を調整します。</translation>
    </message>
    <message>
        <source>DSC_ZOOM_VIEW</source>
        <translation>ズーム</translation>
    </message>
    <message>
        <source>DSC_RESET_VIEW</source>
        <translation>ビューのポイントを復元します。</translation>
    </message>
    <message>
        <source>LBL_TOOLBAR_LABEL</source>
        <translation>表示操作</translation>
    </message>
</context>
<context>
    <name>GraphicsView_Viewer</name>
    <message>
        <source>SEND_BACKWARD</source>
        <translation>背面へ移動</translation>
    </message>
    <message>
        <source>BRING_TO_FRONT</source>
        <translation>最前面へ移動</translation>
    </message>
    <message>
        <source>PROPERTIES</source>
        <translation>プロパティ</translation>
    </message>
    <message>
        <source>REMOVE_IMAGES</source>
        <translation>画像を削除します。</translation>
    </message>
    <message>
        <source>TEST_CROP_OPERATOR</source>
        <translation>作物、テスト オペレーター</translation>
    </message>
    <message>
        <source>ADD_IMAGE</source>
        <translation>画像を追加します。</translation>
    </message>
    <message>
        <source>TEST_FUSE_OPERATOR</source>
        <translation>ヒューズ、テスト オペレーター</translation>
    </message>
    <message>
        <source>CHANGE_BGCOLOR</source>
        <translation>背景を変更する.</translation>
    </message>
    <message>
        <source>BRING_FORWARD</source>
        <translation>前面へ移動</translation>
    </message>
    <message>
        <source>SEND_TO_BACK</source>
        <translation>最背面へ移動</translation>
    </message>
</context>
<context>
    <name>GraphicsView_ViewManager</name>
    <message>
        <source>GRAPHICS_VIEW_TITLE</source>
        <translation>グラフの段階: %M - 可視化: %V</translation>
    </message>
</context>
</TS>
